export const actionTypes = {
  FETCH_ROWS_IN_WORK: 'FETCH_ROWS_IN_WORK',
  FETCH_ROWS_READY: 'FETCH_ROWS_READY',
  ADD_EMPTY_ROW: 'ADD_EMPTY_ROW',
  DELETE_ROW: 'DELETE_ROW',
  MARK_ROW_READY: 'MARK_ROW_READY',
  MARK_ROW_UNREADY: 'MARK_ROW_UNREADY',
  SAVE_ROW_TO_SERVER: 'SAVE_ROW_TO_SERVER',
  SET_ONE_C_ID: 'SET_ONE_C_ID',
  TOGGLE_DONE: 'TOGGLE_DONE',
};
